### ISSUE TITLE
Development Status

### ISSUE THREAD

**Issue by dahagag** [hurik/JGeagle#1]
Hi,
Is this project still active and is there any room for improvement if I want to add some features myself or should I start a new fork?

**Comment by hurik** [comment]
hi muhamada,

at the moment I doesn't do anything with eagle, so I doesn't use it. But I would be happy when someone improves it.

I will look after pull requests or I can add you as collaborator so you can directly push to the repo. Which way do you prefer?

Bye,
Andreas

**Comment by dahagag** [comment]
Well, if I make any progress I'll create a pull request and if things goes well I can be a collaborator
